language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

env:
  - DJANGO_VERSION='Django>=1.4,<1.5'
  - DJANGO_VERSION='Django>=1.5,<1.6'
  - DJANGO_VERSION='Django>=1.6,<1.7'
  - DJANGO_VERSION='Django>=1.7,<1.8'
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'
  - DJANGO_VERSION='Django>=1.10,<1.11'
  - DJANGO_VERSION='Django>=1.11,<1.12'
  - DJANGO_VERSION='Django>=2.0,<2.1'
  - DJANGO_VERSION='Django>=2.1,<2.2'
  - DJANGO_VERSION='Django>=2.2,<2.3'

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.0,<2.1'  # unsupported
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.1,<2.2'  # unsupported
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.2,<2.3'  # unsupported
    - python: "3.4"
      env: DJANGO_VERSION='Django>=1.4,<1.5'  # unsupported
    - python: "3.4"
      env: DJANGO_VERSION='Django>=2.1,<2.2'  # unsupported
    - python: "3.4"
      env: DJANGO_VERSION='Django>=2.2,<2.3'  # unsupported
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.4,<1.5'  # unsupported
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.5,<1.6'  # expects html.parser.HTMLParseError
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.6,<1.7'  # expects html.parser.HTMLParseError
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.7,<1.8'  # expects html.parser.HTMLParseError
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.4,<1.5'  # unsupported
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.5,<1.6'  # expects html.parser.HTMLParseError
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.6,<1.7'  # expects html.parser.HTMLParseError
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.7,<1.8'  # expects html.parser.HTMLParseError
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.4,<1.5'  # unsupported
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.5,<1.6'  # expects html.parser.HTMLParseError
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.6,<1.7'  # expects html.parser.HTMLParseError
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.7,<1.8'  # expects html.parser.HTMLParseError

before_install:
  - sudo apt-get install libenchant-dev

install:
  - pip install -qU pip setuptools
  - pip install -q $DJANGO_VERSION
  - python setup.py -q install
  - pip install git+https://github.com/colons/wcag-zoo.git

script: python setup.py test
