language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION='Django>=1.4,<1.5'
  - DJANGO_VERSION='Django>=1.5,<1.6'
  - DJANGO_VERSION='Django>=1.6,<1.7'
  - DJANGO_VERSION='Django>=1.7,<1.8'
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.4,<1.5'

before_install:
  - sudo apt-get install libenchant-dev

install:
  - pip install -q $DJANGO_VERSION
  - pip install 'git+https://github.com/rfk/pyenchant.git'
  - python setup.py -q install

script: python setup.py test
